# Generated by Django 4.1.5 on 2023-01-15 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_project_sectors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='technologys',
        ),
    ]
