# Generated by Django 4.1.5 on 2023-01-15 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_project_technologys'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sector',
        ),
    ]
