# Generated by Django 4.1.5 on 2023-01-15 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_delete_sector'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Technology',
        ),
    ]
