# Generated by Django 4.1.5 on 2023-01-15 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_sector_project_technologys_technology_logo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
