# Generated by Django 4.1.5 on 2023-01-15 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='imege_reference',
        ),
    ]
