# Generated by Django 4.1.5 on 2023-01-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_project_sectors_project_technologys'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='imege',
            field=models.ImageField(default=True, upload_to='sector/images'),
            preserve_default=False,
        ),
    ]
