# Generated by Django 4.1.5 on 2023-01-15 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_sector_imege'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sector',
            old_name='imege',
            new_name='image',
        ),
    ]
