# Generated by Django 4.1.5 on 2023-11-26 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_rename_imege_sector_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sectors',
        ),
        migrations.RemoveField(
            model_name='project',
            name='technologys',
        ),
        migrations.DeleteModel(
            name='Sector',
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
    ]
