# Generated by Django 4.1.5 on 2023-12-17 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_remove_project_date_remove_project_sectors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('en_proceso', 'En Proceso'), ('terminado', 'Terminado'), ('pendiente', 'Pendiente')], default='en_proceso', max_length=100),
        ),
    ]
