# Generated by Django 4.1.5 on 2024-01-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('En Proceso', 'En Proceso'), ('Terminado', 'Terminado'), ('Pendiente', 'Pendiente')], default='en_proceso', max_length=100),
        ),
    ]
