# Generated by Django 4.1.5 on 2024-01-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Desarrollando', 'Desarrollando'), ('Terminado', 'Terminado'), ('Pendiente', 'Pendiente')], default='en_proceso', max_length=100),
        ),
    ]
