# Generated by Django 4.1.5 on 2024-01-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_blog_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='my_cv',
            field=models.ImageField(blank=True, upload_to='profile/cv/'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_important',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
