# Generated by Django 4.1.5 on 2024-01-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_alter_blog_image_alter_profile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='my_cv',
            field=models.URLField(blank=True),
        ),
    ]
